# Use root/example as user/password credentials
version: '3.7'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fa
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    networks:
      - superset_default

networks:
  superset_default:
    external: true